apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: video-service:latest # Substitua  imagem
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              value: SEU_ACCESS_KEY # Substitua chave
            - name: AWS_SECRET_ACCESS_KEY
              value: SEU_SECRET_KEY # Substitua chave
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"