apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-process-video
  name: deployment-process-video
  namespace: video-system
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-process-video
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate      
  template:
    metadata:
      labels:
        app: app-process-video
    spec:
      containers:
        - name: app-process-video
          image: 857378965163.dkr.ecr.us-east-1.amazonaws.com/spv/process-video:latest
          imagePullPolicy: Always
          env:
          - name: env
            value: prod
          - name: AWS_REGION
            value: us-east-1
          - name: FILE_CONFIG
            value: /app/src/main/resources/application.properties
          - name: JAVA_OPTS
            value: -Xmx512m -Xms512m -XX:MaxRAM=512m -Duser.timezone=GMT-3 -Dnetworkaddress.cache.ttl=60
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 600m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 640Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

